Controllers/CategoriesController.cs
using CoreBusiness;
using Microsoft.AspNetCore.Authorization;

//using MedBilling.Models;
using Microsoft.AspNetCore.Mvc;
using UseCases.CategoriesUseCases;
using UseCases.CategoriesUSeCases;

namespace MedBilling.Controllers
{
    [Authorize(Policy = "Inventory")]
    public class CategoriesController : Controller
    {
        private readonly IViewCategoriesUseCase viewCategoriesUseCase;
        private readonly IViewSelectedCategoryUseCase viewSelectedCategoryUseCase;
        private readonly IEditCategoryUseCase editCategoryUseCase;
        private readonly IAddCategoryUseCase addCategoryUseCase;
        private readonly IDeleteCategoryUseCase deleteCategoryUseCase;

        public CategoriesController(
            IViewCategoriesUseCase viewCategoriesUseCase,
            IViewSelectedCategoryUseCase viewSelectedCategoryUseCase,
            IEditCategoryUseCase editCategoryUseCase,
            IAddCategoryUseCase addCategoryUseCase,
            IDeleteCategoryUseCase deleteCategoryUseCase)
        {
            this.viewCategoriesUseCase = viewCategoriesUseCase;
            this.viewSelectedCategoryUseCase = viewSelectedCategoryUseCase;
            this.editCategoryUseCase = editCategoryUseCase;
            this.addCategoryUseCase = addCategoryUseCase;
            this.deleteCategoryUseCase = deleteCategoryUseCase;
        }
        public IActionResult Index()
        {
            //var categories = CategoriesRepository.GetCategories();
            var categories = viewCategoriesUseCase.Execute();
            return View(categories);
        }
        //By default [HttpGet] method
        public IActionResult Edit(int? id) 
        {
            //if (id.HasValue)
            //    return new ContentResult { Content = id.ToString() };
            //else
            //    return new ContentResult { Content = "null content" };

            //var category = new Category { CategoryId = id.HasValue ? id.Value : 0 };

            ViewBag.Action = "edit";

            //var category = CategoriesRepository.GetCategoryById(id.HasValue ? id.Value : 0);

            var category = viewSelectedCategoryUseCase.Execute(id.HasValue ? id.Value : 0);

            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                //CategoriesRepository.UpdateCategory(category.CategoryId, category);
                editCategoryUseCase.Execute(category.CategoryId, category);
                return RedirectToAction(nameof(Index));
            }
			ViewBag.Action = "edit";
			return View(category);
        }



        public IActionResult Add() 
        {
            ViewBag.Action = "add";

            return View(); 
        }

        [HttpPost]
		public IActionResult Add(Category category)
		{
            if (ModelState.IsValid) 
            {
                //CategoriesRepository.AddCategory(category);
                addCategoryUseCase.Execute(category);
                return RedirectToAction(nameof(Index));
            }
			ViewBag.Action = "add";
			return View(category);
		}

        public IActionResult Delete(int categoryId)
        {
            //CategoriesRepository.DeleteCategory(categoryId);
            deleteCategoryUseCase.Execute(categoryId);
            return RedirectToAction(nameof(Index));
        }
	}
}

Controllers/ProductsController.cs
//using MedBilling.Models;
using CoreBusiness;
using MedBilling.ViewModels;
using Microsoft.AspNetCore.Mvc;
using UseCases.CategoriesUSeCases;
using UseCases;
using Microsoft.AspNetCore.Authorization;

namespace MedBilling.Controllers
{
	[Authorize(Policy = "Inventory")]
	public class ProductsController : Controller
	{
		private readonly IAddProductUseCase addProductUseCase;
		private readonly IEditProductUseCase editProductUseCase;
		private readonly IDeleteProductUseCase deleteProductUseCase;
		private readonly IViewSelectedProductUseCase viewSelectedProductUseCase;
		private readonly IViewProductsUseCase viewProductsUseCase;
		private readonly IViewCategoriesUseCase viewCategoriesUseCase;

		public ProductsController(
			IAddProductUseCase addProductUseCase,
			IEditProductUseCase editProductUseCase,
			IDeleteProductUseCase deleteProductUseCase,
			IViewSelectedProductUseCase viewSelectedProductUseCase,
			IViewProductsUseCase viewProductsUseCase,
			IViewCategoriesUseCase viewCategoriesUseCase)
		{
			this.addProductUseCase = addProductUseCase;
			this.editProductUseCase = editProductUseCase;
			this.deleteProductUseCase = deleteProductUseCase;
			this.viewSelectedProductUseCase = viewSelectedProductUseCase;
			this.viewProductsUseCase = viewProductsUseCase;
			this.viewCategoriesUseCase = viewCategoriesUseCase;
		}

		public IActionResult Index()
		{
            //var products = ProductsRepository.GetProducts(loadCategory: true);
			var products = viewProductsUseCase.Execute(loadCategory: true);

			return View(products);
		}

        public IActionResult Edit(int id)
        {

            ViewBag.Action = "edit";
			//var products = ProductsRepository.GetProductById(id.HasValue ? id.Value : 0);
			//return View(products);
			var selectedProduct = viewSelectedProductUseCase.Execute(id);

			var productViewModel = new ProductViewModel
            {
				//Product = ProductsRepository.GetProductById(id) ?? new Product(),
				//Categories = CategoriesRepository.GetCategories()

				Product = viewSelectedProductUseCase.Execute(id) ?? new Product(),
				Categories = viewCategoriesUseCase.Execute()
			};
            return View(productViewModel);
        }

        [HttpPost]
        public IActionResult Edit(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
				//ProductsRepository.UpdateProduct(productViewModel.Product.ProductId, productViewModel.Product);
				editProductUseCase.Execute(productViewModel.Product.ProductId, productViewModel.Product);
				return RedirectToAction(nameof(Index));
            }
			ViewBag.Action = "edit";
			//productViewModel.Categories = CategoriesRepository.GetCategories();
			productViewModel.Categories = viewCategoriesUseCase.Execute();

			return View(productViewModel);
        }



        public IActionResult Add()
        {
            ViewBag.Action = "add";

            var productViewModel = new ProductViewModel
            {
                //Categories = CategoriesRepository.GetCategories()
                Categories = viewCategoriesUseCase.Execute()
			}; 

            return View(productViewModel);
        }

        [HttpPost]
        public IActionResult Add(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
				//ProductsRepository.AddProduct(productViewModel.Product);
				addProductUseCase.Execute(productViewModel.Product);
                return RedirectToAction(nameof(Index));
            }
			ViewBag.Action = "add";
			//productViewModel.Categories = CategoriesRepository.GetCategories();
			productViewModel.Categories = viewCategoriesUseCase.Execute(); 
            return View(productViewModel);
        }

        public IActionResult Delete(int productid)
        {
			//ProductsRepository.DeleteProduct(productid);
			deleteProductUseCase.Execute(productid);
			return RedirectToAction(nameof(Index));
        }

        //To connect with the sales page through _Products partial View
        //public IActionResult ProductsByCategoryPartial(int categoryId)
        //{  
        //    var products = ProductsRepository.GetProductsByCategoryId(categoryId);
            
        //    return PartialView("_Products", products);
        //    //return View(); 
        //}

    }
}

Controllers/SalesController.cs
//using MedBilling.Models;
using CoreBusiness;
using MedBilling.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using UseCases.CategoriesUSeCases;
using UseCases.ProductsUseCases;
using UseCases;
using Microsoft.AspNetCore.Authorization;

namespace MedBilling.Controllers
{
	[Authorize(Policy = "Cashiers")]   //Only cashiers can access the sales page
	public class SalesController : Controller
    {

		private readonly IViewCategoriesUseCase viewCategoriesUseCase;
		private readonly IViewSelectedProductUseCase viewSelectedProductUseCase;
		private readonly ISellProductUseCase sellProductUseCase;
		private readonly IViewProductsInCategoryUseCase viewProductsInCategoryUseCase;

		public SalesController(IViewCategoriesUseCase viewCategoriesUseCase,
			IViewSelectedProductUseCase viewSelectedProductUseCase,
			ISellProductUseCase sellProductUseCase,
			IViewProductsInCategoryUseCase viewProductsInCategoryUseCase)
		{
			this.viewCategoriesUseCase = viewCategoriesUseCase;
			this.viewSelectedProductUseCase = viewSelectedProductUseCase;
			this.sellProductUseCase = sellProductUseCase;
			this.viewProductsInCategoryUseCase = viewProductsInCategoryUseCase;
		}

		public IActionResult Index()
        {
            var salesViewModel = new SalesViewModel
            {
				//Categories = CategoriesRepository.GetCategories()
				Categories = viewCategoriesUseCase.Execute()
			};

			return View(salesViewModel);
        }

        public IActionResult SellProductPartial(int productId)
        {
			//var product = ProductsRepository.GetProductById(productId);
			var product = viewSelectedProductUseCase.Execute(productId);
			return PartialView("_SellProduct",product);
        }

        public IActionResult Sell(SalesViewModel salesViewModel)
        {
            if (ModelState.IsValid) 
            {

				//Code to sell the product/ Transactions Record

				//           var prod = ProductsRepository.GetProductById(salesViewModel.SelectedProductId);
				//           if (prod != null) 
				//           {
				//TransactionRepository.Add(
				//                   "Cashier1",
				//                   //patientName,
				//                   salesViewModel.SelectedProductId,
				//                   prod.Name,
				//                   prod.Price.HasValue?prod.Price.Value:0,
				//                   prod.Quantity.HasValue?prod.Quantity.Value:0,
				//                   salesViewModel.QuantityToSell);

				//               prod.Quantity -= salesViewModel.QuantityToSell;
				//               ProductsRepository.UpdateProduct(salesViewModel.SelectedProductId, prod);
				//           }

				// Sell the product
				sellProductUseCase.Execute(
					"cashier1",
					salesViewModel.SelectedProductId,
					salesViewModel.QuantityToSell);
			}

			//var product = ProductsRepository.GetProductById(salesViewModel.SelectedProductId);
			//salesViewModel.SelectedCategoryId = (product?.CategoryId == null) ? 0 : product.CategoryId.Value;
			//salesViewModel.Categories = CategoriesRepository.GetCategories();
			
			var product = viewSelectedProductUseCase.Execute(salesViewModel.SelectedProductId);
			salesViewModel.SelectedCategoryId = (product?.CategoryId == null) ? 0 : product.CategoryId.Value;
			salesViewModel.Categories = viewCategoriesUseCase.Execute();
			
			return View("Index",salesViewModel);
        }

		//To connect with the sales page through _Products partial View
		public IActionResult ProductsByCategoryPartial(int categoryId)
		{
			//var products = ProductsRepository.GetProductsByCategoryId(categoryId);
			var products = viewProductsInCategoryUseCase.Execute(categoryId);

			return PartialView("_Products", products);
			//return View(); 
		}

	}
}

Controllers/TransactionsController.cs
using MedBilling.Models;
using MedBilling.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UseCases;

namespace MedBilling.Controllers
{
	//[Authorize]
	public class TransactionsController : Controller
    {
		private readonly ISearchTransactionsUseCase searchTransactionsUseCase;

		public TransactionsController(ISearchTransactionsUseCase searchTransactionsUseCase)
		{
			this.searchTransactionsUseCase = searchTransactionsUseCase;
		}

		public IActionResult Index()
        {
            TransactionsViewModel transactionsViewModel = new TransactionsViewModel();
            return View(transactionsViewModel);
        }

        public IActionResult Search(TransactionsViewModel transactionsViewModel)
        {
            //var transactions = TransactionRepository.Search(
            //    transactionsViewModel.CashierName ?? string.Empty,
            //    transactionsViewModel.StartDate,
            //    transactionsViewModel.EndDate);

			var transactions = searchTransactionsUseCase.Execute(
				transactionsViewModel.CashierName ?? string.Empty,
				transactionsViewModel.StartDate,
				transactionsViewModel.EndDate);

			transactionsViewModel.Transactions = transactions;

            return View("Index", transactionsViewModel);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MedBilling</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MedBilling.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MedBilling</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Sales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="pb-3">
            @RenderSection("title",false)
            <hr />
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MedBilling - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.7.0.min.js" 
            integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
            crossorigin="anonymous"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>